import 'package:get/get.dart';

class ArabicLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ar': {
      //AnimatedBottomBarPage
      "cart": "السلة",
      "login": "تسجيل الدخول",
      "donate": "تبرع",
      "Donate": "تبرع",
      "menu": "القائمة",
      "my events": "فعالياتي",
      "home": "الرئيسية",
      "projects events": "المشاريع والفعاليات",
      "tasks": "المهام",
      "profile": "الملف الشخصي",
      "settings": "الإعدادات",
      "about us": "حول",
      "logout": "تسجيل الخروج",
      "confirm logout": "تأكيد تسجيل الخروج",
      "logout message": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
      "cancel": "إلغاء",
      "user name": "المستخدم",
      "user email": "User@gmail.com",
      //Settings
      "settings": "الإعدادات",
      "change mode": "تغيير الوضع",
      "dark mode": "الوضع الليلي",
      "light mode": "الوضع النهاري",
      "change language": "تغيير اللغة",
      "English": "الإنجليزية",
      "Arabic": "العربية",
      "Theme Changed": "تم تغيير النمط",
      "Language Changed": "تم تغيير اللغة",
      //HomePageVolunteer
      "Khotwa": "خطوة",
      "education support": "دعم التعليم",
      "refugee assistance": "مساعدة اللاجئين",
      "community water well": "بئر مياه المجتمع",
      "organization charity": "جمعية خيرية",
      "organization relief": "مجموعة الإغاثة",
      "organization water": "مؤسسة المياه",
      "status accept": "مقبول",
      "my events": "فعالياتي",
      "Recommended": "موصى به",
      "top projects": "أهم المشاريع",
      "view all": "عرض الكل",
      "search": "بحث...",
      "View Details": "عرض تفاصيل",
      "Details": "عرض تفاصيل",
      "paid": "المدفوع: @amount",
      "remaining": "المتبقي: @amount",
      //profile
      "Milad AlNser": "ميلاد النصير",
      "Edit": "تعديل",
      "Save": "حفظ",
      "Full Name": "الاسم الكامل",
      "Gender": "الجنس",
      "Male": "ذكر",
      "Female": "أنثى",
      "Email": "البريد الإلكتروني",
      "Phone": "رقم الهاتف",
      "Birth Date": "تاريخ الميلاد",
      "Address": "العنوان",
      "City": "المدينة",
      "Areas of Interest": "مجالات الاهتمام",
      "Availability": "التوافر",
      "Preferred Time": "الوقت المفضل",
      "Previous Experience": "الخبرات السابقة",
      "Skills": "المهارات",
      "Motivation": "الدافع",
      "Contact Name": "اسم جهة الاتصال",
      "Relationship": "العلاقة",
      "Home": "الرئيسية",
      "Menu": "القائمة",
      "Login": "تسجيل الدخول",
      "Donate": "التبرع",
      "Cart": "السلة",
      "Settings": "الإعدادات",
      "About Us": "من نحن",
      "Logout": "تسجيل الخروج",
      "John Doe": "جون دو",
      "Jane Doe": "جين دو",
      "Sister": "أخت",
      "Health, Education": "الصحة والتعليم",
      "Mon, Wed, Fri": "الإثنين، الأربعاء، الجمعة",
      "5-8 hours/week": "5-8 ساعات/أسبوع",
      "Blood donation volunteer": "متطوع تبرع بالدم",
      "First aid, Event organizing": "الإسعافات الأولية، تنظيم الفعاليات",
      "Helping my community": "مساعدة مجتمعي",
      "Volunteer History": "تاريخ المتطوع",
      "Emergency Contact": "جهة الاتصال للطوارئ",
      "Experience and Skills": "الخبرات والمهارات",
      "Volunteer Info": "معلومات المتطوع",
      "Personal Information": "المعلومات الشخصية",
      "Volunteer Hours": "ساعات التطوع",
      "Ahmed Ali": "أحمد علي",
      "Joined: March 15, 2022": "انضم: 15 مارس 2022",
      "Volunteer Histor": "تاريخ التطوع",
      "Volunteer Hourse": "ساعات التطوع",
      "Active Volunteer": "متطوع نشط",
      "Warnings": "التحذيرات",
      "Participated and Current Campaigns": "المشاركات والحملات الحالية",
      "Active": "نشط",
      "Completed": "مكتمل",
      "Hours: ": " عدد الساعات: ",
      "Role: ": "الدور: ",
      //task
      "My Tasks": "مهامي",
      "Cancel": "إلغاء",
      "Confirm": "تأكيد",
      "In Progress": "قيد التنفيذ",
      "completed": "مكتمل",
      "Pending": "قيد التحميل",
      "Update Status": "تحديث الحالة",
      "Are you sure you want to update the task status?":
          "هل أنت متأكد أنك تريد تحديث حالة المهمة؟",
      "Decline Task": "رفض المهمة",
      "Are you sure you want to decline this task?":
          "هل أنت متأكد أنك تريد رفض هذه المهمة؟",
      "community outreach call": "الاتصال بالمراكز المجتمعية",
      "prepare registration":
          "تحضير مكاتب التسجيل وحزم الترحيب للمتطوعين الجدد.",
      "call community centers":
          "الاتصال بالمراكز المجتمعية لتأكيد المشاركة في حملة توزيع الطعام القادمة.",
      "Supervisor": "المشرف",
      "Event": "الفعالية",
      "Due": "تاريخ الاستحقاق",
      "Assigned": "مُسند",
      "Welcome event setup":"انشاء حدث",
        "create new task": "إنشاء مهمة جديدة",
  "title": "العنوان",
  "description": "الوصف",
  "enter task name": "أدخل اسم المهمة",
  "enter task description": "أدخل وصف المهمة",
  "start date": "تاريخ البداية",
  "due date": "تاريخ الاستحقاق",
  "assign": "إسناد",
  "no date selected": "No date selected",
  "Select Date": "Select Date",
    },
  };
}
