import 'package:get/get.dart';

class ArabicLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ar': {
      //AnimatedBottomBarPage
      "cart": "السلة",
      "login": "تسجيل الدخول",
      "continue as a guest": "متابعة كمضيف",
      "OR": "أو",
      "donate": "تبرع",
      "Donate": "تبرع",
      "menu": "القائمة",
      "my events": "فعالياتي",
      "home": "الرئيسية",
      "projects events": "المشاريع والفعاليات",
      "Events": "فعاليات",
      "Projects": "مشاريع",
      "tasks": "المهام",
      "Target money": "الهدف",
      "profile": "الملف الشخصي",
      "Donated": "تبرع",
      "Remaining": "متبقي",
      "settings": "الإعدادات",
      "about us": "حول",
      "logout": "تسجيل الخروج",
      "confirm logout": "تأكيد تسجيل الخروج",
      "logout message": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
      "cancel": "إلغاء",
      "user name": "المستخدم",
      "user email": "User@gmail.com",
      //Settings
      "settings": "الإعدادات",
      "change mode": "تغيير الوضع",
      "dark mode": "الوضع الليلي",
      "light mode": "الوضع النهاري",
      "change language": "تغيير اللغة",
      "English": "الإنجليزية",
      "Arabic": "العربية",
      "Theme Changed": "تم تغيير النمط",
      "Language Changed": "تم تغيير اللغة",
      //HomePageVolunteer
      "Khotwa": "خطوة",
      "education support": "دعم التعليم",
      "refugee assistance": "مساعدة اللاجئين",
      "community water well": "بئر مياه المجتمع",
      "organization charity": "جمعية خيرية",
      "organization relief": "مجموعة الإغاثة",
      "organization water": "مؤسسة المياه",
      "status accept": "مقبول",
      "my events": "فعالياتي",
      "Recommended": "موصى به",
      "top projects": "أهم المشاريع",
      "view all": "عرض الكل",
      "search": "بحث...",
      "View Details": "عرض تفاصيل",
      "Apology Confirmation": "تأكيد الاعتذار",
      "Are you sure you want to apologize for the event":
          "هل متأكد من الاعتذار ",
          "Event Details":"تفاصيل فعالية",
      "Details": "عرض تفاصيل",
      "paid": "المدفوع: @amount",
      "remaining": "المتبقي: @amount",
      //profile
      "Milad AlNser": "ميلاد النصير",
      "Edit": "تعديل",
      "Save": "حفظ",
      "Full Name": "الاسم الكامل",
      "Gender": "الجنس",
      "Male": "ذكر",
      "Female": "أنثى",
      "Email": "البريد الإلكتروني",
      "Phone": "رقم الهاتف",
      "Birth Date": "تاريخ الميلاد",
      "Address": "العنوان",
      "City": "المدينة",
      "Areas of Interest": "مجالات الاهتمام",
      "Availability": "التوافر",
      "Preferred Time": "الوقت المفضل",
      "Previous Experience": "الخبرات السابقة",
      "Skills": "المهارات",
      "Motivation": "الدافع",
      "Contact Name": "اسم جهة الاتصال",
      "Relationship": "العلاقة",
      "Home": "الرئيسية",
      "Menu": "القائمة",
      "Login": "تسجيل الدخول",
      "Donate": "التبرع",
      "Cart": "السلة",
      "Settings": "الإعدادات",
      "About Us": "من نحن",
      "Logout": "تسجيل الخروج",
      "John Doe": "جون دو",
      "Jane Doe": "جين دو",
      "Sister": "أخت",
      "Health, Education": "الصحة والتعليم",
      "Mon, Wed, Fri": "الإثنين، الأربعاء، الجمعة",
      "5-8 hours/week": "5-8 ساعات/أسبوع",
      "Blood donation volunteer": "متطوع تبرع بالدم",
      "First aid, Event organizing": "الإسعافات الأولية، تنظيم الفعاليات",
      "Helping my community": "مساعدة مجتمعي",
      "Volunteer History": "تاريخ المتطوع",
      "Emergency Contact": "جهة الاتصال للطوارئ",
      "Experience and Skills": "الخبرات والمهارات",
      "Volunteer Info": "معلومات المتطوع",
      "Personal Information": "المعلومات الشخصية",
      "Volunteer Hours": "ساعات التطوع",
      "Ahmed Ali": "أحمد علي",
      "Joined: March 15, 2022": "انضم: 15 مارس 2022",
      "Join":"انضم",
      "funded":"ممول",
      "Start Date":"وقت البداية",
      "End Date":"وقت النهاية",
      "Volunteer Histor": "تاريخ التطوع",
      "Volunteer Hourse": "ساعات التطوع",
      "Active Volunteer": "متطوع نشط",
      "Warnings": "التحذيرات",
      "Participated and Current Campaigns": "المشاركات والحملات الحالية",
      "Active": "نشط",
      "Completed": "مكتمل",
      "Hours: ": " عدد الساعات: ",
      "Role: ": "الدور: ",
      //task
      "My Tasks": "مهامي",
      "Cancel": "إلغاء",
      "Confirm": "تأكيد",
      "In Progress": "قيد التنفيذ",
      "completed": "مكتمل",
      "Pending": "قيد التحميل",
      "Update Status": "تحديث الحالة",
      "Are you sure you want to update the task status?":
          "هل أنت متأكد أنك تريد تحديث حالة المهمة؟",
      "Decline Task": "رفض المهمة",
      "Are you sure you want to decline this task?":
          "هل أنت متأكد أنك تريد رفض هذه المهمة؟",
      "community outreach call": "الاتصال بالمراكز المجتمعية",
      "prepare registration":
          "تحضير مكاتب التسجيل وحزم الترحيب للمتطوعين الجدد.",
      "call community centers":
          "الاتصال بالمراكز المجتمعية لتأكيد المشاركة في حملة توزيع الطعام القادمة.",
      "Supervisor": "المشرف",
      "Event": "الفعالية",
      "Due": "تاريخ الاستحقاق",
      "Assigned": "مُسند",
      "Welcome event setup": "انشاء حدث",
      "create new task": "إنشاء مهمة جديدة",
      "title": "العنوان",
      "description": "الوصف",
      "enter task name": "أدخل اسم المهمة",
      "enter task description": "أدخل وصف المهمة",
      "start date": "تاريخ البداية",
      "due date": "تاريخ الاستحقاق",
      "assign": "إسناد",
      "no date selected": "لم يتم اختيار تاريخ",
      "Select Date": "اختر التاريخ",
      "Date": "تاريخ",
      "Time": "الوقت",
      "Location": "الموقع",
      "Volunteers": "المتطوعين",
      "Apologize": "اعتذار",
      "Project Details":"تفاصيل مشروع",
      "Status: Active":"حالة نشطة",
      "Upcoming Events":"الفعاليات القادمة",
      "Donation Progress":"ميزانية التبرع",
      "Collected:":"تم جمع",
      "Target:":"الهدف",
      "Donate Now":"تبرع الان",
      "Scan QR Code":"امسح رمز QR",
      "Scan a code":"امسح الرمز",
      "Scanned:":"مسح",
      "Result:":"النتيجة",
      "Login Required":"يتوجب تسجيل الدخول",
      "Please log in to continue with the donation process.":"سجل دخول لمتابعة عملية التبرع",
      "Login successful!":"تم تسجيل الدخول بنجاح",
      "Donor Login":"تسجيل دخول المتبرع",
      "Name":"الاسم",
      "Email":"البريد الالكتروني",
"Enter your full name":"ادخل كامل الاسم",
"Name must be at least 2 characters":" يجب الاسم على الاقل ان يكون محرفين",
"Name is required":"الاسم ضروري",
"Email is required":"البريد الالكتروني ضروري",
"Enter a valid email":"ادخل بريد الكتروني صحيح",
"Enter your email":"ادخل بريدك الالكتروني",
"Error":"غلط",
"Passwords do not match.":"كلمة السر غير متطابقة",
"OTP is missing.":"رمز OTP غير موجود",
"Please enter the new password and its confirmation.":"ادخل كلمة السر الجديدة",
"New password is required":"كلمة السر الجديدة ضرورية ",
"Password must be at least 6 characters":"يجب ان تكون كلمة السر على الاقل من 6 محارف",
"Please confirm your password":"يجب تأكيد كلمة السر",
"Passwords do not match":"كلمات السر غير متطابقة",
"Changing Password":"تغيير كلمة السر",
"New password":"كلمة السر الجديدة",
"Change":"تغيير",
"Confirm New Password":"تأكيد كلمة السر الجديدة",
"We are done":"خلصنا"
  }
  };
}