import 'package:get/get.dart';

class EnglishLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      //AnimatedBottomBarPage
      "menu": "Menu",
      "login": "Login",
      "donate": "Donate",
      "Donate": "Donate",
      "cart": "Cart",
      "my events": "My Events",
      "home": "Home",
      "projects events": "Projects, Events",
      "Projects":"Projects",
      "Events":"Events",
      "Target money":"Target money",
      "Donated":"Donated",
      "Remaining":"Remaining",
      "tasks": "Tasks",
      "profile": "Profile",
      "settings": "Settings",
      "about us": "About Us",
      "logout": "Logout",
      "confirm logout": "Confirm Logout",
      "logout message": "Are you sure you want to log out?",
      "cancel": "Cancel",
      "user name": "User",
      "user email": "User@gmail.com",
      //Settings
      "settings": "Settings",
      "change mode": "Change Mode",
      "dark mode": "Dark Mode",
      "light mode": "Light Mode",
      "change language": "Change Language",
      "english": "English",
      "arabic": "Arabic",
      "Theme Changed": "Theme Changed",
      "Language Changed": "Language Changed",
      //HomePageVolunteer
      "Khotwa": "Khotwa",
      "education support": "Education Support",
      "refugee assistance": "Refugee Assistance",
      "community water well": "Community Water Well",
      "organization charity": "Charity Org",
      "organization relief": "Relief Group",
      "organization water": "Water Foundation",
      "status accept": "Accept",
      "my events": "My Events",
      "Start Date":"Start Date",
      "End Date":"End Date",
      "Event Details":"Event Details",
      "Join":"Join",
      "funded":"funded",
      "Apology Confirmation":"Apology Confirmation",
      "Are you sure you want to apologize for the event":
      "Are you sure you want to apologize for the event",
      "Recommended": "Recommended",
      "top projects": "Top Projects",
      "view all": "View All",
      "search": "Search...",
      "View Details": "View Details",
      "paid": "Paid: @amount",
      "remaining": "Remaining: @amount",
      //profile
      "Milad AlNser": "Milad AlNser",
      "Edit": "Edit",
      "Save": "Save",
      "Full Name": "Full Name",
      "Gender": "Gender",
      "Male": "Male",
      "Female": "Female",
      "Email": "Email",
      "Phone": "Phone",
      "Birth Date": "Birth Date",
      "Address": "Address",
      "City": "City",
      "Areas of Interest": "Areas of Interest",
      "Availability": "Availability",
      "Preferred Time": "Preferred Time",
      "Previous Experience": "Previous Experience",
      "Skills": "Skills",
      "Motivation": "Motivation",
      "Contact Name": "Contact Name",
      "Relationship": "Relationship",
      "Home": "Home",
      "Menu": "Menu",
      "Login": "Login",
      "OR":"OR",
      "continue as a guest":"continue as a guest",
      "Donate": "Donate",
      "Cart": "Cart",
      "Settings": "Settings",
      "About Us": "About Us",
      "Logout": "Logout",
      "John Doe": "John Doe",
      "Jane Doe": "Jane Doe",
      "Sister": "Sister",
      "Health, Education": "Health, Education",
      "Mon, Wed, Fri": "Mon, Wed, Fri",
      "5-8 hours/week": "5-8 hours/week",
      "Blood donation volunteer": "Blood donation volunteer",
      "First aid, Event organizing": "First aid, Event organizing",
      "Helping my community": "Helping my community",
      "Volunteer History": "Volunteer History",
      "Emergency Contact": "Emergency Contact",
      "Experience and Skills": "Experience and Skills",
      "Volunteer Info": "Volunteer Info",
      "Personal Information": "Personal Information",
      "Volunteer Hours": "Volunteer Hours",
      "Ahmed Ali": "Ahmed Ali",
      "Joined: March 15, 2022": "Joined: March 15, 2022",
      "Volunteer Histor": "Volunteer History",
      "Volunteer Hourse": "Volunteer Hours",
      "Active Volunteer": "Active Volunteer",
      "Warnings": "Warnings",
      "Participated and Current Campaigns":
          "Participated and Current Campaigns",
      "Active": "Active",
      "Completed": "Completed",
      "Hours: ": "Hours: ",
      "Role: ": "Role: ",
      //Task
      "My Tasks": "My Tasks",
      "Decline Task": "Decline Task",
      "Cancel": "Cancel",
      "Confirm": "Confirm",
      "In Progress": "in progress",
      "Pending": "Pending",
      "pending": "pending",
      "Welcome event setup":"Welcome event setup",
      "completed": "completed",
      "Update Status": "Update Status",
      "Are you sure you want to update the task status?":
          "Are you sure you want to update the task status?",
      "Are you sure you want to decline this task?":
          "Are you sure you want to decline this task?",
      "community outreach call": "Community Outreach Call",
      "prepare registration":
          "Prepare registration desks and welcome packets for new volunteers.",
      "call community centers":
          "Call community centers to confirm participation in the upcoming food drive.",
      "Supervisor": "Supervisor",
      "Event": "Event",
      "Due": "Due",
      "Assigned": "Assigned",
  "title": "Title",
  "description": "Description",
  "enter task name": "Enter task name",
  "enter task description": "Enter task description",
  "start date": "Start Date",
  "due date": "Due Date",
  "assign": "Assign",
   "create new task": "Create New Task",
  "no date selected": "No date selected",
  "Select Date": "Select Date",
"Date":"Date",
"Time":"Time",
"Location":"Location",
"Volunteers":"Volunteers",
"Project Details":"Project Details",
"Status: Active":"Status: Active",
"Upcoming Events":"Upcoming Events",
"Donation Progress":"Donation Progress",
"Apologize":"Apologize",
"Target:":"Target:",
"Collected:":"Collected:",
"Donate Now":"Donate Now",
"Scan QR Code":"Scan QR Code",
"Scan a code":"Scan a code",
"Result:":"Result:",
"Scanned:":"Scanned:",
"Login Required":"Login Required",
"Please log in to continue with the donation process.":"Please log in to continue with the donation process.",
"Login successful!":"Login successful!",
"Donor Login":"Donor Login",
"Name":"Name",
"Email":"Email",
"Enter your full name":"Enter your full name",
"Name must be at least 2 characters":"Name must be at least 2 characters",
"Name is required":"Name is required",
"Email is required":"Email is required",
"Enter a valid email":"Enter a valid email",
"Enter your email":"Enter your email",
"Error":"Error",
"Passwords do not match.":"Passwords do not match.",
"OTP is missing.":"OTP is missing.",
"Please enter the new password and its confirmation.":"Please enter the new password and its confirmation.",
"New password is required":"New password is required",
"Password must be at least 6 characters":"Password must be at least 6 characters",
"Please confirm your password":"Please confirm your password",
"Passwords do not match":"Passwords do not match",
"Changing Password":"Changing Password",
"New password":"New password",
"Change":"Change",
"Confirm New Password":"Confirm New Password",
"We are done":"We are done",





    },
  };
}
