// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLOzCXTOhbuksrlTtxVDg2bTlR9lX0SXA',
    appId: '1:1011165907371:web:c50e98086bd9c4f722aaee',
    messagingSenderId: '1011165907371',
    projectId: 'khotwanew',
    authDomain: 'khotwanew.firebaseapp.com',
    storageBucket: 'khotwanew.firebasestorage.app',
    measurementId: 'G-NZ705VP5G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJrC_4DZyHyvG_5KnZ1a1DNY4azT7XtTw',
    appId: '1:1011165907371:android:d884f7a0c0bc5d8222aaee',
    messagingSenderId: '1011165907371',
    projectId: 'khotwanew',
    storageBucket: 'khotwanew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJZ7yuXvKP1PyBmWfnXS3K82y4Vi0FaJE',
    appId: '1:1011165907371:ios:3a9dd0e74b714b7322aaee',
    messagingSenderId: '1011165907371',
    projectId: 'khotwanew',
    storageBucket: 'khotwanew.firebasestorage.app',
    iosBundleId: 'com.example.khotwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJZ7yuXvKP1PyBmWfnXS3K82y4Vi0FaJE',
    appId: '1:1011165907371:ios:3a9dd0e74b714b7322aaee',
    messagingSenderId: '1011165907371',
    projectId: 'khotwanew',
    storageBucket: 'khotwanew.firebasestorage.app',
    iosBundleId: 'com.example.khotwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLOzCXTOhbuksrlTtxVDg2bTlR9lX0SXA',
    appId: '1:1011165907371:web:44b10034b80f3ca322aaee',
    messagingSenderId: '1011165907371',
    projectId: 'khotwanew',
    authDomain: 'khotwanew.firebaseapp.com',
    storageBucket: 'khotwanew.firebasestorage.app',
    measurementId: 'G-KMR4D14XGC',
  );

}